apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: snia
  labels:
   app: snia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snia
  template:
    metadata:
      labels:
        app: snia
    spec:
      containers:
      - name: snia
        image: containeraizationregistry.azurecr.io/snialatest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: mysecret
